# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: PulseSecure.Ivanti
PackageVersion: 22.2.1295
PackageLocale: en-US
Publisher: Ivanti, Inc.
PackageName: Ivanti Secure Access Client
License: PulseSecure
ShortDescription: PulseSecure Ivanti VPN Client
ManifestType: defaultLocale
ManifestVersion: 1.2.0

